from src.summarization.llm_summarization import summarize_all_topics
import smtplib
from email.message import EmailMessage
from dotenv import load_dotenv
import os 

def generate_html(topic_summaries):
    html = """
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background-color: #f9f9f9; }
            h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
            .topic { background-color: white; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
            .topic h2 { color: #2c3e50; margin-top: 0; }
            .paper-count { color: #7f8c8d; font-size: 14px; margin-bottom: 10px; }
            .tags { display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: 15px; }
            .tag-group { background-color: #f0f4f8; border-radius: 6px; padding: 8px 12px; font-size: 13px; }
            .tag-group strong { color: #2980b9; }
            .summary { color: #34495e; line-height: 1.6; border-left: 4px solid #3498db; padding-left: 12px; }
            .footer { text-align: center; color: #95a5a6; font-size: 12px; margin-top: 30px; }
        </style>
    </head>
    <body>
        <h1>🧬 Pulsar — Weekly PubMed Digest</h1>
        <p style="color: #7f8c8d;">Here are the most important research developments from the past week.</p>
    """

    for title, topic_item in topic_summaries.items():
        count = topic_item["count"]
        tags = topic_item["tags"]
        summary = topic_item["summary"]

        chemicals = ", ".join(tags.get("chemicals", [])) or "none"
        diseases = ", ".join(tags.get("diseases", [])) or "none"
        genes = ", ".join(tags.get("genes/proteins", [])) or "none"
        cell_types = ", ".join(tags.get("cell_types", [])) or "none"
        cell_lines = ", ".join(tags.get("cell_lines", [])) or "none"

        html += f"""
        <div class="topic">
            <h2>{title}</h2>
            <p class="paper-count">📄 {count} papers this week</p>
            <div class="tags">
                <div class="tag-group"><strong>💊 Chemicals:</strong> {chemicals}</div>
                <div class="tag-group"><strong>🦠 Diseases:</strong> {diseases}</div>
                <div class="tag-group"><strong>🧬 Genes/Proteins:</strong> {genes}</div>
                <div class="tag-group"><strong>🔬 Cell Types:</strong> {cell_types}</div>
                <div class="tag-group"><strong>🧫 Cell Lines:</strong> {cell_lines}</div>
            </div>
            <p class="summary">{summary}</p>
        </div>
        """

    html += """
        <div class="footer">
            <p>Generated by Pulsar — Automated Scientific Literature Digest</p>
        </div>
    </body>
    </html>
    """

    return html

def send_email():
    load_dotenv()
    topic_summaries = summarize_all_topics()

    sender_email = os.getenv("EMAIL_ADDRESS")
    receiver_email = os.getenv("EMAIL_ADDRESS")
    password = os.getenv("APP_PASSWORD")

    msg = EmailMessage()
    msg["Subject"] = "Weekly Digest of PubMed"
    msg["From"] = sender_email
    msg["To"] = receiver_email 

    msg.set_content("Please use a browser that supports HTML content. Thank you!")
    html_content = generate_html(topic_summaries)
    msg.add_alternative(html_content, subtype="html")

    try: 
        with smtplib.SMTP("smtp.gmail.com", 587) as server: 
            server.starttls()
            server.login(sender_email, password)
            server.send_message(msg)
        print("Email sent successfully!")
    except Exception as e: 
        print(f"Failed to send email: {e}")

send_email()